steps:
  - name: node:10.15.1
    entrypoint: yarn
    args: ["install"]
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: gsutil
    args:
      [
        "cp",
        "gs://relay-resource-private/relay-cms-key.json",
        "./keys/relay-cms-key.json",
      ]
  - name: node:10.15.1
    entrypoint: yarn
    args: ["build"]
  - name: "node"
    entrypoint: "./node_modules/.bin/firebase"
    args: ["deploy"]
